apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-deployment
  namespace: default
  labels:
    app: locust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      labels:
        app: locust
    spec:
      containers:
      - name: locust
        image: mdczw/my-locust
        ports:
        - containerPort: 8089