apiVersion: v1
kind: Service
metadata:
  name: locust-service
  namespace: default
spec:
  selector:
    app: locust
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8089
    targetPort: 8089

